Online_Learning_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learningApp.urls')),
    path('authentications/', include('authentications.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentications/urls.py
from django.urls import path
from . import views

app_name ='authentications'

urlpatterns = [
   
    path('register_user', views.register_user, name ='register_user'),
    path('loggin', views.loggin, name ='loggin'),
    path('logout', views.logout, name ='logout'),
    
]

learningApp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name = 'index'),
    path('all_courses/', views.all_courses, name = 'all_courses'),
    path('curriculum_form/', views.curriculum_form, name = 'curriculum_form'),
    path('create_course/', views.create_course, name = 'create_course'),
    path('category_detail/<int:category_id>/', views.category_detail, name = 'category_detail'),
    path('course_detail/<int:course_id>/', views.course_detail, name = 'course_detail'),
    path('review_course/<int:course_id>/', views.review_course, name = 'review_course'),
    path('reply_comment/<int:course_id>/<int:review_id>/', views.reply_comment, name = 'reply_comment'),
    path('reply_review/<int:review_id>/', views.reply_review, name = 'reply_review'),
    path('likereview/<int:review_id>/', views.likereview, name = 'likereview'),
    path('likereply/<int:replyreview_id>/', views.likereply, name = 'likereply'),
    path('lessonpage/<int:course_id>/', views.lessonpage, name = 'lessonpage'),
    path('quiz_page/<int:course_id>/', views.quiz_page, name = 'quiz_page'),
    path('view_score/<int:course_id>/', views.view_score, name='view_score'),
    path('generate_certificate/<int:course_id>/', views.generate_certificate, name='generate_certificate'),
    path('generate_certificate_pdf/<int:certificate_id>/', views.generate_certificate_pdf, name='generate_certificate_pdf'),
    path('subscription', views.news_sub, name='subscription'),
    path('search', views.search, name='search'),
    path('rate_instructor/<int:instructor_id>/', views.rate_instructor, name='rate_instructor'),
    # path('get_enrollment_count/', views.get_enrollment_count, name = 'get_enrollment_count'),
    path('enrolled_courses_view/', views.enrolled_courses_view, name = 'enrolled_courses_view'),
    path('remove_from_cart/<int:enroll_id>/', views.remove_from_cart, name = 'remove_from_cart'),

]

learningApp/forms.py
from learningApp.models import Instructor, Curriculum
from django.forms import ModelForm

class InstructorForm(ModelForm):
    
    class Meta:
        model = Instructor
        fields = ['name', 'photo', 'comment']
        
class CurriculumForm(ModelForm):
    
    class Meta:
        model = Curriculum
        fields = ['course', 'heading', 'heading_intro', 'sub_heading', 'sub_heading_intro']
        
    

learningApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from learningApp.models import *
from learningApp.forms import InstructorForm, CurriculumForm
from django.contrib import messages
from django.forms import formset_factory
from django.db.models import Count, Avg, Sum, Q
from django.urls import reverse
from django.db import transaction
from reportlab.pdfgen import canvas
from io import BytesIO
from learningApp.pdf import generate_certificate_pdf
from fpdf import FPDF
from django.http import HttpResponse
from tempfile import NamedTemporaryFile
from PIL import Image
import os
from django.conf import settings
from django.http import JsonResponse

def remove_from_cart(request, enroll_id):
    user = request.user
    enroll = get_object_or_404(Enrollment, id=enroll_id)
    if user == enroll.user:
        enroll.delete()
        messages.info(request, f'you removed the course "{enroll.course.title}" from your cart')
        return redirect('enrolled_courses_view')

def enrolled_courses_view(request):
    user = request.user
    enrolled_courses = Enrollment.objects.filter(user=user).order_by('-enrolled_at')

    # Update is_enroll to false
    enrollment_notification = EnrollmentNotification.objects.filter(user=user)
    add_to_cart = EnrollmentNotification.objects.filter(user=user, is_enroll=True).aggregate(counts=Count('enroll'))

    for enroll in enrollment_notification:
        enroll.is_enroll = False
        enroll.save()

    context = {
        'enrolled_courses': enrolled_courses,
        'cart':add_to_cart,

        }
    return render(request, 'learningApp/enrolled_courses.html', context)


def rate_instructor(request, instructor_id):
    user = request.user
    instructor_id = Instructor.objects.get(id = instructor_id)

    existing_review = reviewInstructor.objects.filter(user=user, instructor=instructor_id)

    with transaction.atomic():

        if request.method == 'POST':
            rating = request.POST.get('rating')
            comment = request.POST.get('comment')

            if existing_review:
                for existing_reviews in existing_review:
                    existing_reviews.rating = rating
                    existing_reviews.comment = comment
                    existing_reviews.save()


            rate_instructor, update = reviewInstructor.objects.update_or_create(
                user = user,
                rating = rating,
                comment = comment,
                instructor = instructor_id,
                defaults={'rating': rating, 'comment': comment},
            )
            # if updated:
            #     rate_instructor.save()
            messages.info(request, 'Thank you for rating this instructor. Do you wish to enroll another course?')

            course = instructor_id.course_set.first()
            # get_course_elements = instructor_id.course_set.first()

            if course:
                return redirect(reverse('generate_certificate', args = [course.id]))
        context = {
            'instructors':instructor_id,
        }
        return render(request, 'learningApp/rate_instructor.html', context)

def search(request):
    if request.method =='GET':
        search = request.GET.get('search')
        search_query = Course.objects.filter(Q(title__icontains = search)) if search else None
    if search:
        return render(request, 'learningApp/search.html', {'searches':search_query})
    messages.success(request, f'No course with name {search} yet!')
    return redirect('all_courses')
def news_sub(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if subscriptionNewsletter.objects.filter(email = email).exists():
            messages.info(request, f'Some has already subscribe with this email {email}')
            return redirect('index')
        elif email is None:
            messages.info(request, f'You did not enter email')
            return redirect('index')
        subscriptionNewsletter.objects.create(email = email)
        messages.success(request, 'You subscribed to our newsletter')
        return redirect('index')
    return redirect('index')



def curriculum_form(request):
    course = Course.objects.all()
    formset= formset_factory(CurriculumForm)
    if request.method =='POST':
        form = formset(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request, 'Curriculum created add more')
            return redirect('curriculum_form')
        messages.info(request, 'Erro saving curriculum')
        return redirect('curriculum_form')
    form = CurriculumForm()
    context = {
        'forms':formset,
        'courses':course,
    }
    return render(request, 'learningApp/create_curriculum.html', context)

def review_course(request, course_id):
    the_course_id = Course.objects.get(id=course_id)
    user = request.user

    if not user.is_authenticated:
        messages.error(request, 'You are not permitted here!')
        return redirect('index')

    if request.method == 'POST':
        name = request.POST.get('name')
        comment = request.POST.get('comment')
        rating = request.POST.get('rating')
        photo = request.FILES.get('photo')

        if the_course_id and the_course_id.title:
            course_review =Review(user=user, name = name, course =the_course_id, comment=comment,
                            rating = rating, photo=photo)
            course_review.save()

            messages.info(request, 'Thank you for review this course')
            return redirect('index')

    return render(request, 'learningApp/review.html')


def create_course(request):
    user = request.user
    all_category_list= Category.objects.all()
    if not user.is_instructor:
        messages.error(request, 'You are not permitted here!')
        return redirect('index')
    # if user.is_instructor:
    if request.method == 'POST':
        title = request.POST.get('title')
        price = request.POST.get('price')
        description = request.POST.get('description')
        requirement = request.POST.get('requirement')
        duration = request.POST.get('duration')
        category_id = request.POST.get('category')
        target_audience = request.POST.get('target_audience')
        thumbnail = request.POST.get('thumbnail')

        course =Course(user=user, title = title, price =price, description=description,
                        requirement = requirement, duration=duration,
                        target_audience=target_audience, thumbnail=thumbnail)
        course.save()


        course.categories.add(category_id)
        messages.info(request, 'Saved!')
        return redirect('index')

    context={
        'categories':all_category_list,
    }
    return render(request, 'learningApp/create_course.html', context)

def index(request):
    user =request.user
    intro = Intro.objects.first()
    menu = Menu.objects.all()
    events = upcomingEvent.objects.all()[:3]
    instructors = Instructor.objects.all().order_by('-post_date')[:4]

    add_to_cart = EnrollmentNotification.objects.filter(user=user, is_enroll = True).aggregate(counts = Count('enroll'))
    categories_with_enrollment = Category.objects.annotate(enrollment_count=Count('course__enrollment'))
    # get_url = reverse('category_detail', args =[categories_with_enrollment.first, course.first])
    if request.method == 'POST':
        name = request.POST.get('name')
        # course_id = request.POST['course']  # Get the selected course ID
        comment = request.POST.get('comment')
        photo = request.POST.get('photo')  # Use request.FILES to handle file uploads

        if user.is_instructor and Instructor.objects.filter(name=name).exists:
            messages.info(request, 'You already filled the Instructor detail. Add you courses!')
            return redirect('create_course')
        instructor = Instructor(name=name, comment=comment, photo=photo)
        instructor.save()

        if instructor:
            messages.info(request, 'Instructor data saved!')
            return redirect('create_course')
        messages.info(request, 'Error!')
        return redirect('index')


    context = {
        # 'get_url':get_url,
        'events':events,
        'intros': intro,
        'menus': menu,
        'categories': categories_with_enrollment,
        'instructors':instructors,
        'cart':add_to_cart,
    }

    return render(request, 'learningApp/index.html', context)

def all_courses(request):
    user = request.user
    course_cat = Category.objects.all()

    course = Course.objects.all().order_by('created_at')[:3]

    galary = Course.objects.all().order_by('created_at')[:9]

    add_to_cart = EnrollmentNotification.objects.filter(user=user, is_enroll=True).aggregate(counts=Count('enroll'))

    if request.method =='GET':
        search = request.GET.get('search')
        search_course = Course.objects.filter(Q(title__icontains = search)) if search else None
        if not search:
            messages.info(request, 'Not available')
    context = {
        'searches':search_course,
        'galary':galary,
        'courses':course,

        'categories':course_cat,
        'cart':add_to_cart,
    }
    return render(request, 'learningApp/courses.html', context)

def category_detail(request, category_id):
    category_id = Category.objects.get(id = category_id)
    get_all_course_with_the_same_category = category_id.course_set.all()
    courses_with_user_count = category_id.course_set.annotate(user_count=Count('enrollment', distinct=True),
            average_rating=Avg('review__rating'))
    get_latest_course = Category.objects.all().order_by('-update_date')[0:2]
    events = upcomingEvent.objects.all()[:3]

    add_to_cart = EnrollmentNotification.objects.filter(user=request.user, is_enroll=True).aggregate(counts=Count('enroll'))

    instructors =Instructor.objects.all()[:4]
    context ={
        'events':events,

learningApp/templates/base/learningApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>SCL Academy {% block title%}{% endblock %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Unicat project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'learningApp/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/main_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/enroll.css' %}">

<!-- <link href="plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
<link href="{% static 'learningApp/plugins/colorbox/colorbox.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/courses.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/courses_responsive.css' %}">
<!--
	 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

<link href="{% static 'learningApp/plugins/colorbox/colorbox.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/course.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/course_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/quiz.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'learningApp/styles/certificate.css' %}">

<body>
    <header class="header">
			
		<!-- Top Bar -->
		<div class="top_bar">
			<div class="top_bar_container">
				<div class="container">
					<div class="row">
						<div class="col">
							<div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
								<ul class="top_bar_contact_list">
									<li><div class="question">Have any questions?</div></li>
									<li>
										<i class="fa fa-phone" aria-hidden="true"></i>
										<div>+(234) 8134622388</div>
									</li>
									<li>
										<i class="fa fa-envelope-o" aria-hidden="true"></i>
										<div>mathiaswilfred7@gmail.com</div>
									</li>
								</ul>
								{% if user.is_authenticated %}
								<div class="top_bar_login ml-auto">
									<div class="login_button"><a href="{% url 'authentications:logout' %}">Logout</a></div>
								</div>
								{% else %}
								<div class="top_bar_login ml-auto">
									<div class="login_button"><a href="{% url 'authentications:register_user' %}">Register</a></div>
								</div>
								<div class="top_bar_login ml-auto">
									<div class="login_button"><a href="{% url 'authentications:loggin' %}">Login</a></div>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>				
		</div>

		<!-- Header Content -->
		<div class="header_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="logo_container">
								<a href="#">
									<div class="logo_text">Kingdom<span>Academy</span></div>
								</a>
							</div>
							{% if user.is_authenticated %}
							<nav class="main_nav_contaner ml-auto">
								<ul class="main_nav">
									<li class="active"><a href="{% url 'index' %}">Home</a></li>
									<li><a href="">About</a></li>
									<li><a href="{% url 'all_courses' %}">Courses</a></li>
									<li><a href="">Blog</a></li>
									<li><a href="#">Page</a></li>
									<li><a href="">Contact</a></li>
								</ul>
								<div class="search_button"><i class="fa fa-search" aria-hidden="true"></i></div>

                                    <div class="shopping_cart">
                                        <a href="{% url 'enrolled_courses_view' %}">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                            <span class="enrollment_count text-danger">
                                                {{ cart.counts }}
                                            </span>
                                        </a>
                                    </div>

							</nav>
							{% endif %}

						</div>
<!--						message-->
						{% if messages %}
						<div class="container">
							<div class="row">
								<div class="col">
									<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
										{% for message in messages %}
											{{ message }}
										{% endfor %}
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
								</div>
							</div>
						</div>
						{% endif %}
<!--						end-->
					</div>
				</div>
			</div>
		</div>

		<!-- Header Search Panel -->
		<div class="header_search_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_search_content d-flex flex-row align-items-center justify-content-end">
							<form action="{% url 'search' %}" class="header_search_form" method="get">
								<input type="search" name="search" class="search_input" placeholder="Search" required="required">
								<button class="header_search_button d-flex flex-column align-items-center justify-content-center">
									<i class="fa fa-search" aria-hidden="true"></i>
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>			
		</div>			
	</header>

	<!-- Menu -->

	<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
		<div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
		<div class="search">
			<form action="#" class="header_search_form menu_mm">
				<input type="search" class="search_input menu_mm" placeholder="Search" required="required">
				<button class="header_search_button d-flex flex-column align-items-center justify-content-center menu_mm">
					<i class="fa fa-search menu_mm" aria-hidden="true"></i>
				</button>
			</form>
		</div>

	</div>
	

    {% block content %}
    {% endblock %}
	<!-- Newsletter -->

	<div class="newsletter">
		<div class="newsletter_background" style="background-image:url({% static 'learningApp/images/newsletter_background.jpg' %})"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter_container d-flex flex-lg-row flex-column align-items-center justify-content-start">

						<!-- Newsletter Content -->
						<div class="newsletter_content text-lg-left text-center">

							<div class="newsletter_title">sign up for news and offers</div>
							<div class="newsletter_subtitle">Subcribe to lastest smartphones news & great deals we offer</div>
						</div>

						<!-- Newsletter Form -->
						<div class="newsletter_form_container ml-lg-auto">
							<form action="{% url 'subscription' %}" id="newsletter_form" class="newsletter_form d-flex flex-row align-items-center justify-content-center" method="post">
								{% csrf_token %}
								<input type="email" name = "email" class="newsletter_input" placeholder="Your Email" required="required">
								<button type="submit" class="newsletter_button">subscribe</button>
							</form>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

    <!-- Footer -->

	<footer class="footer">
		<div class="footer_background" style="background-image:url({% static 'learningApp/images/footer_background.png' %})"></div>
		<div class="container">
			<div class="row footer_row">
				<div class="col">
					<div class="footer_content">
						<div class="row">

							<div class="col-lg-3 footer_col">
					
								<!-- Footer About -->
								<div class="footer_section footer_about">
									<div class="footer_logo_container">
										<a href="#">
											<div class="footer_logo_text">Kindom<span>Academy</span></div>
										</a>
									</div>
									<div class="footer_about_text">
										<p>Lorem ipsum dolor sit ametium, consectetur adipiscing elit.</p>
									</div>
									<div class="footer_social">
										<ul>
											<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
										</ul>
									</div>
								</div>
								
							</div>

							<div class="col-lg-3 footer_col">
					
								<!-- Footer Contact -->
								<div class="footer_section footer_contact">
									<div class="footer_title">Contact Us</div>
									<div class="footer_contact_info">
										<ul>
											<li>Email: mathiaswilfred7@gmail.com</li>
											<li>Phone:  +(234) 8134622388</li>
											<li>40 Dafa Kwali Area Council. FCT Abuja, Nigeria</li>
										</ul>
									</div>
								</div>
								
							</div>

							<div class="col-lg-3 footer_col">
					
								<!-- Footer links -->
								<div class="footer_section footer_links">
									<div class="footer_title">Contact Us</div>
									<div class="footer_links_container">
										<ul>
											<li><a href="index.html">Home</a></li>
											<li><a href="about.html">About</a></li>
											<li><a href="contact.html">Contact</a></li>
											<li><a href="#">Features</a></li>
											<li><a href="courses.html">Courses</a></li>
											<li><a href="#">Events</a></li>
											<li><a href="#">Gallery</a></li>
											<li><a href="#">FAQs</a></li>
										</ul>
									</div>
								</div>
								
							</div>

							<div class="col-lg-3 footer_col clearfix">
					
								<!-- Footer links -->
								<div class="footer_section footer_mobile">
									<div class="footer_title">Mobile</div>
									<div class="footer_mobile_content">
										<div class="footer_image"><a href="#"><img src="{% static 'learningApp/images/mobile_1.png' %}" alt=""></a></div>
										<div class="footer_image"><a href="#"><img src="{% static 'learningApp/images/mobile_2.png' %}" alt=""></a></div>
									</div>
								</div>
								
							</div>

						</div>
					</div>
				</div>
			</div>

			<div class="row copyright_row">
				<div class="col">
					<div class="copyright d-flex flex-lg-row flex-column align-items-center justify-content-start">
						<div class="cr_text"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Learning Platform <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Wilfred Mathias</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
						<div class="ml-lg-auto cr_links">
							<ul class="cr_list">
								<li><a href="#">Copyright notification</a></li>
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

    <script src="{% static 'learningApp/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'learningApp/styles/bootstrap4/popper.js' %}"></script>
    <script src="{% static 'learningApp/styles/bootstrap4/bootstrap.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/greensock/TweenMax.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/greensock/TimelineMax.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/greensock/animation.gsap.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/greensock/ScrollToPlugin.min.js' %}"></script>
    <script src="{% static 'learningApp/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
    <script src="{% static 'learningApp/plugins/easing/easing.js' %}"></script>
    <script src="{% static 'learningApp/plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="{% static 'learningApp/js/custom.js' %}"></script>
	
	<script src="{% static 'learningApp/plugins/colorbox/jquery.colorbox-min.js' %}"></script>
	<script src="{% static 'learningApp/js/courses.js' %}"></script>

	<script src="{% static 'learningApp/js/course.js' %}"></script>

</body>
</html>

learningApp/templates/base/learningApp/event.html
{% load static %}
<!-- Events -->

<div class="events">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="section_title_container text-center">
					<h2 class="section_title">Upcoming events</h2>
					<div class="section_subtitle"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel gravida arcu. Vestibulum feugiat, sapien ultrices fermentum congue, quam velit venenatis sem</p></div>
				</div>
			</div>
		</div>
		<div class="row events_row">

			<!-- Event -->
			{% for event in events %}
			<div class="col-lg-4 event_col">

				<div class="event event_left">
					<div class="event_image"><img src="{{ event.thumbnail.url }}" alt=""></div>
					<div class="event_body d-flex flex-row align-items-start justify-content-start">
						<div class="event_date">
							<div class="d-flex flex-column align-items-center justify-content-center trans_200">
								<div class="event_day trans_200">{{ event.event_date_future|date:"d" }}</div>
								<div class="event_month trans_200">{{ event.event_date_future|date:"M" }}</div>
							</div>
						</div>
						<div class="event_content">
							<div class="event_title"><a href="#">{{ event.title }}</a></div>
							<div class="event_info_container">
								<div class="event_info"><i class="fa fa-clock-o" aria-hidden="true"></i><span>{{ event.time }}</span></div>
								<div class="event_info"><i class="fa fa-map-marker" aria-hidden="true"></i><span>{{ event.address }}</span></div>
								<div class="event_text">
									<p>{{ event.description | truncatewords:15 }}</p>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
			{% endfor %}


		</div>
	</div>
</div>

<!-- Team -->

<div class="team">
	<div class="team_background parallax-window" data-parallax="scroll" data-image-src="{% static 'learningApp/images/team_background.jpg' %}" data-speed="0.8"></div>
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="section_title_container text-center">
					<h2 class="section_title">The Best Tutors in Town</h2>
					<div class="section_subtitle"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel gravida arcu. Vestibulum feugiat, sapien ultrices fermentum congue, quam velit venenatis sem</p></div>
				</div>
			</div>
		</div>
		<div class="row team_row">

			<!-- Team Item -->
			{% for instructor in instructors %}
			<div class="col-lg-3 col-md-6 team_col">
				<div class="team_item">
					<div class="team_image"><img src="{{ instructor.photo.url }}" alt=""></div>
					<div class="team_body">
						<div class="team_title"><a href="#">{{ instructor.name }}</a></div>
						<div class="team_subtitle">{{ instructor.position }}</div>
						<div class="social_list">
							<ul>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
			<!-- Team Item -->

		</div>
	</div>
</div>